name: Performance Test

on:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run JMeter Tests
      run: |
        chmod +x ./path/to/your/jmeter/bin/jmeter.sh
        ./path/to/your/jmeter/bin/jmeter.sh -n -t path/to/your/test-plan.jmx -l results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl
