name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: jpetstore_adding-more-itemtocart_2.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
      - name: Create artifact files
        run: |
          mkdir -p reults/dir-1
          mkdir -p reults/dir-2
          echo "Lorem ipsum dolor sit amet" > reults/dir-1/file1.txt
          echo "Hello world from file #2" > reults/dir-2/file2.txt
